openapi: 3.0.0
info:
  title: API de Gestão de Produtos
  version: 2.0.0
  description: API para gerenciamento de produtos e inventário
  contact:
    name: Equipe de Desenvolvimento
    email: dev@empresa.com
servers:
  - url: https://api.produtos.empresa.com/v2
    description: Servidor de Produção
  - url: https://api-qa.produtos.empresa.com/v2
    description: Servidor de QA
paths:
  /products:
    get:
      summary: Listar produtos
      description: Retorna lista paginada de produtos com filtros
      tags:
        - Produtos
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: category
          in: query
          schema:
            type: string
        - name: minPrice
          in: query
          schema:
            type: number
        - name: maxPrice
          in: query
          schema:
            type: number
      responses:
        '200':
          description: Lista de produtos
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
      security:
        - apiKey: []
    post:
      summary: Criar produto
      tags:
        - Produtos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '201':
          description: Produto criado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          $ref: '#/components/responses/BadRequest'
      security:
        - apiKey: []
  /products/{productId}:
    get:
      summary: Buscar produto por ID
      tags:
        - Produtos
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Produto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          $ref: '#/components/responses/NotFound'
      security:
        - apiKey: []
    put:
      summary: Atualizar produto
      tags:
        - Produtos
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '200':
          description: Produto atualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          $ref: '#/components/responses/NotFound'
      security:
        - apiKey: []
    delete:
      summary: Excluir produto
      tags:
        - Produtos
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Produto excluído
        '404':
          $ref: '#/components/responses/NotFound'
      security:
        - apiKey: []
  /products/{productId}/inventory:
    get:
      summary: Consultar estoque do produto
      tags:
        - Inventário
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Informações de estoque
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inventory'
      security:
        - apiKey: []
    put:
      summary: Atualizar estoque
      tags:
        - Inventário
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryUpdate'
      responses:
        '200':
          description: Estoque atualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inventory'
      security:
        - apiKey: []
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        category:
          type: string
        sku:
          type: string
        active:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    ProductInput:
      type: object
      required:
        - name
        - price
        - category
        - sku
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 200
        description:
          type: string
          maxLength: 1000
        price:
          type: number
          format: double
          minimum: 0
        category:
          type: string
        sku:
          type: string
          pattern: '^[A-Z0-9-]+$'
        active:
          type: boolean
          default: true
    Inventory:
      type: object
      properties:
        productId:
          type: string
          format: uuid
        quantity:
          type: integer
        reservedQuantity:
          type: integer
        availableQuantity:
          type: integer
        warehouse:
          type: string
        lastUpdated:
          type: string
          format: date-time
    InventoryUpdate:
      type: object
      required:
        - quantity
      properties:
        quantity:
          type: integer
          minimum: 0
        warehouse:
          type: string
    Pagination:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        total:
          type: integer
        totalPages:
          type: integer
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: array
          items:
            type: string
  responses:
    BadRequest:
      description: Requisição inválida
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Recurso não encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Não autorizado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key
