-- Carga de Runbooks
USE auditoria_db;

-- Limpar dados existentes
DELETE FROM runbooks;

-- Inserir 20 runbooks de exemplo
INSERT INTO runbooks (
  id, sigla, descricao_resumida, finalidade, tipo_runbook,
  acessos_necessarios, validacoes_antes_iniciar, ferramentas_necessarias,
  comandos, pontos_atencao, checks_intermediarios, criterios_sucesso, criterios_falha,
  validacoes_obrigatorias, verificacao_logs, status_esperado_aplicacao, notificacoes_necessarias,
  scripts_relacionados, jobs_associados, url_localizacao_scripts, condicoes_automacao,
  prints_logs_necessarios, arquivos_gerados, tempo_medio_execucao,
  principais_riscos, acoes_preventivas, acoes_corretivas_rapidas
) VALUES

-- 1. Deploy de Aplicacao
(UUID(), 'DEPL-00001', 'Deploy Aplicacao Web em Producao', 'Realizar deploy de nova versao da aplicacao web no ambiente de producao', 'Deploy',
  'Acesso SSH aos servidores de producao, Permissoes de deploy no Jenkins, Acesso ao repositorio Git',
  'Verificar se existe backup recente, Validar testes automatizados passaram, Confirmar janela de manutencao agendada',
  'Jenkins, Git, Docker, Kubernetes kubectl',
  'git pull origin main\ndocker build -t app:v1.2.3 .\ndocker push registry/app:v1.2.3\nkubectl apply -f deployment.yaml\nkubectl rollout status deployment/app',
  'Verificar se ha usuarios ativos antes do deploy, Manter comunicacao com equipe de suporte, Monitorar logs durante rollout',
  'kubectl get pods -w, Verificar healthcheck endpoint, Validar metricas no Grafana',
  'Pods em estado Running, Healthcheck retornando 200, Usuarios conseguem acessar aplicacao',
  'Pods em estado CrashLoopBackOff, Erro 500 em healthcheck, Usuarios reportando indisponibilidade',
  'Executar smoke tests, Verificar metricas de latencia, Validar integracao com APIs externas',
  'Conferir logs de erro no Kibana, Validar ausencia de exceptions, Verificar logs de acesso',
  'Aplicacao respondendo em todos os endpoints, Metricas dentro dos parametros normais',
  'Notificar equipe de desenvolvimento sobre sucesso, Atualizar status no Slack, Enviar email para stakeholders',
  'deploy.sh, rollback.sh, smoke-tests.sh',
  'Jenkins Job Deploy-Production, Cron backup-pre-deploy',
  'https://github.com/company/scripts/deploy',
  'Executar apenas em janela de manutencao, Requer aprovacao do gestor, Validar testes antes',
  'Screenshot do kubectl get pods, Logs do deployment, Print do healthcheck',
  'deployment.yaml atualizado, Logs de deploy no Jenkins, Release notes',
  '15 minutos',
  'Indisponibilidade da aplicacao, Perda de dados, Incompatibilidade de versao',
  'Realizar deploy em horario de baixo uso, Executar backup antes, Testar em staging',
  'Executar rollback imediato, Restaurar versao anterior, Comunicar incidente'),

-- 2. Backup de Banco de Dados
(UUID(), 'BACK-00001', 'Backup Completo Banco de Dados MySQL', 'Executar backup completo do banco de dados de producao', 'Backup',
  'Acesso root ao servidor MySQL, Permissoes de escrita no storage de backup, Acesso ao script de backup',
  'Verificar espaco disponivel em disco, Validar que nao ha manutencao agendada, Confirmar janela de backup',
  'mysqldump, gzip, AWS CLI para S3',
  'mysqldump -u root -p --all-databases --single-transaction > backup.sql\ngzip backup.sql\naws s3 cp backup.sql.gz s3://backups/mysql/$(date +%Y%m%d)',
  'Backup pode impactar performance, Monitorar uso de disco durante execucao',
  'Verificar tamanho do arquivo gerado, Validar integridade do arquivo com md5sum',
  'Arquivo de backup gerado com sucesso, Upload para S3 concluido, Checksum validado',
  'Falha na geracao do backup, Erro no upload para S3, Arquivo corrompido',
  'Testar restauracao do backup em ambiente de testes, Validar consistencia dos dados',
  'Verificar logs do mysqldump, Conferir logs de upload no AWS CLI',
  'Backup disponivel no S3, Arquivo com tamanho esperado',
  'Enviar notificacao de sucesso para time de DBA, Atualizar planilha de controle de backups',
  'backup-mysql.sh, verify-backup.sh',
  'Cron daily-mysql-backup',
  'https://github.com/company/scripts/backup',
  'Executar diariamente as 02:00 AM, Requer espaco minimo de 50GB',
  'Screenshot do comando executado, Log de upload S3',
  'Arquivo backup-YYYYMMDD.sql.gz no S3',
  '45 minutos',
  'Falha no backup e perda de dados, Espaco em disco insuficiente',
  'Monitorar espaco em disco, Testar restauracao mensalmente, Manter multiplas copias',
  'Executar backup manual adicional, Liberar espaco em disco'),

-- 3. Restart de Servico
(UUID(), 'REST-00001', 'Restart Servico API Gateway', 'Reiniciar servico API Gateway apos atualizacao de configuracao', 'Startup / Shutdown',
  'Acesso SSH ao servidor, Permissoes sudo, Acesso ao systemctl',
  'Verificar se ha requisicoes ativas, Validar configuracao antes do restart, Notificar equipe',
  'systemctl, journalctl',
  'sudo systemctl stop api-gateway\nsudo systemctl start api-gateway\nsudo systemctl status api-gateway',
  'Servico pode demorar ate 30s para inicializar completamente, Monitorar logs durante startup',
  'Verificar status do servico, Testar endpoint de health',
  'Servico em estado active (running), Healthcheck retornando 200',
  'Servico failed ou inactive, Healthcheck retornando erro',
  'Validar que todas as rotas estao funcionando, Testar autenticacao',
  'journalctl -u api-gateway -f, Verificar logs de erro',
  'Servico respondendo normalmente, Logs sem erros criticos',
  'Notificar time de desenvolvimento, Atualizar status no monitoramento',
  'restart-api-gateway.sh',
  'Monit restart-api-gateway',
  'https://github.com/company/scripts/services',
  'Executar apenas apos validacao de configuracao',
  'Log do systemctl status, Screenshot do healthcheck',
  'Logs de restart no journalctl',
  '2 minutos',
  'Indisponibilidade do servico, Erro de configuracao impedindo inicio',
  'Validar configuracao antes do restart, Ter plano de rollback',
  'Reverter configuracao anterior, Restaurar backup de config'),

-- 4. Procedimento de Contingencia
(UUID(), 'CONT-00001', 'Contingencia Falha Servidor Principal', 'Ativar servidor secundario em caso de falha do principal', 'Contingência',
  'Acesso aos servidores primario e secundario, Permissoes de alteracao de DNS, Acesso ao load balancer',
  'Confirmar que servidor principal esta realmente indisponivel, Validar que secundario esta operacional',
  'DNS Manager, Load Balancer Console, Monitoramento',
  'Acessar Load Balancer Console\nRemover servidor principal do pool\nAdicionar servidor secundario\nAtualizar registro DNS para apontar para secundario\nValidar roteamento',
  'Mudanca pode levar ate 5 minutos para propagar, Monitorar trafego durante transicao',
  'Verificar propagacao DNS, Validar trafego sendo roteado',
  'Trafego 100% no servidor secundario, DNS atualizado, Usuarios acessando normalmente',
  'DNS nao propagou, Servidor secundario tambem apresenta falha',
  'Executar testes de carga no secundario, Validar todas as funcionalidades',
  'Monitorar logs de acesso, Verificar metricas de performance',
  'Sistema operacional sem degradacao, Metricas dentro do normal',
  'Abrir chamado de incidente, Notificar gestao, Comunicar usuarios',
  'failover.sh, dns-update.sh',
  'Zabbix trigger failover-automation',
  'https://github.com/company/scripts/contingency',
  'Executar apenas em caso de falha confirmada do principal',
  'Screenshot do load balancer, Logs de DNS, Graficos de trafego',
  'Registro de incidente, Logs de failover',
  '10 minutos',
  'Falha simultanea de ambos servidores, Perda de sessoes de usuario',
  'Manter servidores sincronizados, Testar failover mensalmente',
  'Escalar para datacenter alternativo, Comunicar estimativa de recuperacao'),

-- 5. Manutencao Programada
(UUID(), 'MANU-00001', 'Manutencao Aplicacao Patches Seguranca', 'Aplicar patches de seguranca no sistema operacional', 'Operação Programada',
  'Acesso root aos servidores, Permissoes para instalar pacotes',
  'Verificar lista de patches disponiveis, Validar compatibilidade, Agendar janela de manutencao',
  'yum/apt, systemctl, monitoramento',
  'sudo yum update --security\nsudo systemctl reboot\naguardar boot completo\nvalidar servicos',
  'Servidor ficara indisponivel durante reboot, Pode levar ate 10 minutos',
  'Verificar servidor voltou online, Validar todos servicos iniciaram',
  'Servidor online, Todos servicos ativos, Patches instalados',
  'Servidor nao retornou online, Servicos falharam ao iniciar',
  'Testar funcionalidades criticas, Validar integracao com outros sistemas',
  'Verificar logs do sistema, Conferir versoes instaladas',
  'Sistema operacional atualizado, Servicos respondendo normalmente',
  'Notificar conclusao da manutencao, Atualizar documentacao de versoes',
  'update-security-patches.sh',
  'Cron monthly-security-updates',
  'https://github.com/company/scripts/maintenance',
  'Executar mensalmente em janela de manutencao',
  'Lista de patches instalados, Logs de update',
  'Relatorio de patches aplicados',
  '30 minutos',
  'Incompatibilidade de patches, Falha no boot apos atualizacao',
  'Testar patches em ambiente de staging, Ter plano de rollback',
  'Fazer boot em modo de recuperacao, Remover patches problematicos'),

-- Continuar com mais 15 runbooks...
(UUID(), 'MONI-00001', 'Configuracao Alertas Monitoramento', 'Configurar novos alertas no sistema de monitoramento', 'Procedimento de Rotina',
  'Acesso ao Grafana/Prometheus, Conhecimento de PromQL',
  'Definir thresholds apropriados, Validar metricas existem',
  'Grafana, Prometheus, Alertmanager',
  'Acessar Grafana > Alerting\nCriar novo alert rule\nDefinir query PromQL\nConfigurar thresholds\nDefinir canais de notificacao\nSalvar e testar',
  'Testar alerta antes de ativar em producao',
  'Disparar alerta de teste, Verificar notificacao recebida',
  'Alerta configurado e testado, Notificacoes funcionando',
  'Alerta nao dispara, Notificacoes nao chegam',
  'Simular condicao de alerta, Validar todas notificacoes',
  'Verificar logs do Alertmanager',
  'Alert ativo no Grafana, Canais de notificacao configurados',
  'Documentar novo alerta, Treinar equipe',
  'create-alert.sh',
  '',
  'https://github.com/company/monitoring',
  'Validar metricas antes de criar alerta',
  'Screenshot do alert configurado',
  'Arquivo de configuracao do alert',
  '15 minutos',
  'Alerta com muitos falsos positivos, Threshold incorreto',
  'Testar em ambiente de homologacao primeiro',
  'Ajustar threshold, Desabilitar temporariamente'),

(UUID(), 'INCI-00001', 'Tratamento Incidente Alta Latencia', 'Procedimento para investigar e resolver alta latencia na API', 'Tratamento de Incidente',
  'Acesso aos logs, Ferramentas de profiling, APM',
  'Confirmar incidente via monitoramento, Coletar metricas iniciais',
  'Kibana, New Relic, Chrome DevTools',
  'Verificar metricas de latencia no Grafana\nAnalisar logs no Kibana\nExecutar profiling da aplicacao\nIdentificar queries lentas\nOtimizar ou adicionar cache',
  'Pode ser necessario restart da aplicacao',
  'Monitorar latencia apos cada acao',
  'Latencia voltou ao normal, Usuarios nao reportam lentidao',
  'Latencia continua alta, Problema se agrava',
  'Executar testes de carga, Validar todas funcionalidades',
  'Analisar logs de performance',
  'API respondendo em tempo normal',
  'Documentar causa raiz, Criar task para correcao definitiva',
  'diagnose-latency.sh',
  '',
  'https://github.com/company/scripts/troubleshooting',
  'Executar durante incidente de performance',
  'Graficos de latencia, Logs de queries',
  'Relatorio de incidente, Plan de acao',
  '1 hora',
  'Degradacao adicional durante investigacao',
  'Ter ambiente de teste para reproduzir',
  'Aumentar recursos temporariamente, Ativar cache'),

(UUID(), 'SEGU-00001', 'Rotacao Credenciais Banco Dados', 'Rotacionar senhas de acesso ao banco de dados', 'Procedimento de Rotina',
  'Acesso ao banco de dados, Permissoes de alteracao de usuarios',
  'Gerar novas senhas seguras, Identificar aplicacoes que usam credenciais',
  'Password manager, MySQL client',
  'Gerar nova senha forte\nAlterar senha no banco: ALTER USER app_user IDENTIFIED BY nova_senha\nAtualizar credenciais nas aplicacoes\nReiniciar aplicacoes\nValidar conexoes',
  'Aplicacoes ficarao sem acesso durante atualizacao',
  'Testar conexao com novas credenciais',
  'Todas aplicacoes conectando normalmente',
  'Aplicacao falha ao conectar ao banco',
  'Testar todas aplicacoes que usam o banco',
  'Verificar logs de conexao do banco',
  'Conexoes estabelecidas com sucesso',
  'Documentar nova senha no vault, Agendar proxima rotacao',
  'rotate-db-credentials.sh',
  'Cron quarterly-password-rotation',
  'https://github.com/company/security',
  'Executar trimestralmente',
  'Log de alteracao de senha',
  'Registro no vault de senhas',
  '20 minutos',
  'Aplicacoes ficarem sem acesso ao banco',
  'Ter plano de comunicacao, Executar em janela de manutencao',
  'Reverter para senha anterior temporariamente'),

(UUID(), 'MIGR-00001', 'Migracao Dados Entre Ambientes', 'Migrar dados do ambiente de staging para producao', 'Procedimento de Rotina',
  'Acesso aos bancos de dados origem e destino, Permissoes de escrita',
  'Validar integridade dos dados de origem, Fazer backup do destino',
  'mysqldump, psql, data migration scripts',
  'Fazer backup do destino\nExportar dados da origem\nValidar dados exportados\nImportar para destino\nValidar integridade\nAtualizar sequences',
  'Operacao pode demorar dependendo do volume',
  'Conferir contagem de registros, Validar foreign keys',
  'Dados migrados corretamente, Contagens batem',
  'Dados inconsistentes, Foreign keys quebradas',
  'Executar queries de validacao, Testar aplicacao',
  'Conferir logs de importacao',
  'Dados disponiveis e consistentes',
  'Documentar migracao, Atualizar versao do schema',
  'migrate-data.sh, validate-migration.sql',
  '',
  'https://github.com/company/migrations',
  'Sempre fazer backup antes',
  'Logs de migracao, Relatorio de validacao',
  'Dump dos dados migrados',
  '1 hora',
  'Perda ou corrupcao de dados',
  'Testar em ambiente de desenvolvimento primeiro',
  'Restaurar backup, Reverter migracao'),

(UUID(), 'SCAL-00001', 'Escalonamento Horizontal Aplicacao', 'Adicionar novos nos ao cluster da aplicacao', 'Operação Programada',
  'Acesso ao Kubernetes, Permissoes para escalar deployments',
  'Validar capacidade da infraestrutura, Verificar metricas de uso',
  'kubectl, Kubernetes dashboard',
  'kubectl scale deployment app --replicas=5\nkubectl rollout status deployment/app\nvalidar novos pods\ntestar load balancer',
  'Novos pods podem demorar alguns minutos para ficarem prontos',
  'Verificar pods em estado Ready, Testar distribuicao de carga',
  'Todos pods rodando, Carga distribuida uniformemente',
  'Pods em CrashLoopBackOff, Carga nao distribuida',
  'Executar testes de carga, Monitorar metricas',
  'Verificar logs dos novos pods',
  'Cluster escalado e operacional',
  'Atualizar documentacao de capacidade',
  'scale-deployment.sh',
  '',
  'https://github.com/company/kubernetes',
  'Executar durante alta demanda',
  'kubectl get pods output, Metricas de load',
  'Configuracao atualizada do deployment',
  '10 minutos',
  'Recursos insuficientes para novos pods',
  'Monitorar capacidade antes de escalar',
  'Reduzir numero de replicas, Adicionar mais nos'),

(UUID(), 'CERT-00001', 'Renovacao Certificados SSL', 'Renovar certificados SSL antes da expiracao', 'Operação Programada',
  'Acesso aos servidores web, Permissoes para atualizar certificados',
  'Verificar data de expiracao, Gerar CSR se necessario',
  'certbot, openssl, nginx/apache',
  'Gerar novo CSR\nSubmeter para CA\nBaixar certificado assinado\nInstalar no servidor\nRecarregar webserver\nValidar certificado',
  'Pode haver breve interrupcao durante reload',
  'Testar HTTPS, Verificar validade do certificado',
  'Certificado instalado e valido, HTTPS funcionando',
  'Certificado invalido, Erro de configuracao',
  'Testar em todos os navegadores, Validar cadeia de certificados',
  'Verificar logs do webserver',
  'HTTPS funcionando com certificado valido',
  'Agendar proxima renovacao, Atualizar inventario de certificados',
  'renew-ssl-cert.sh',
  'Cron cert-renewal-check',
  'https://github.com/company/certificates',
  'Renovar 30 dias antes da expiracao',
  'Output do openssl verify',
  'Certificado instalado, CSR e chave privada',
  '30 minutos',
  'Expiracao do certificado, Configuracao incorreta',
  'Monitorar data de expiracao, Ter processo automatizado',
  'Usar certificado temporario, Corrigir configuracao'),

(UUID(), 'LOGA-00001', 'Configuracao Rotacao Logs', 'Configurar logrotate para gerenciar logs da aplicacao', 'Procedimento de Rotina',
  'Acesso root ao servidor, Conhecimento de logrotate',
  'Identificar logs a serem rotacionados, Definir politica de retencao',
  'logrotate, cron',
  'Criar arquivo /etc/logrotate.d/app\nDefinir configuracoes de rotacao\nTestar com logrotate -d\nAplicar configuracao\nValidar rotacao',
  'Primeira rotacao pode gerar varios arquivos',
  'Verificar arquivos rotacionados, Validar compressao',
  'Logs rotacionados corretamente, Espaco em disco recuperado',
  'Rotacao falhou, Logs nao comprimidos',
  'Monitorar espaco em disco apos rotacao',
  'Verificar logs do logrotate',
  'Rotacao funcionando conforme configurado',
  'Documentar politica de retencao',
  'setup-logrotate.sh',
  'Cron daily logrotate',
  'https://github.com/company/logging',
  'Configurar antes que disco fique cheio',
  'Arquivo de configuracao do logrotate',
  'Logs rotacionados e comprimidos',
  '15 minutos',
  'Perda de logs importantes, Disco cheio',
  'Definir retencao adequada, Monitorar espaco',
  'Descomprimir logs antigos se necessario'),

(UUID(), 'TUNA-00001', 'Tunning Performance Banco Dados', 'Otimizar configuracoes do banco de dados para melhor performance', 'Procedimento de Rotina',
  'Acesso ao banco de dados, Permissoes para alterar configuracoes',
  'Analisar queries lentas, Coletar metricas de performance',
  'MySQL Workbench, pt-query-digest, mysqltuner',
  'Executar mysqltuner.pl\nAnalisar slow query log\nIdentificar indices faltantes\nOtimizar configuracoes do my.cnf\nReiniciar MySQL\nValidar melhorias',
  'Restart do banco causara breve indisponibilidade',
  'Comparar metricas antes e depois',
  'Performance melhorada, Queries mais rapidas',
  'Performance degradou, Queries ainda lentas',
  'Executar queries de teste, Monitorar por 24h',
  'Analisar slow query log novamente',
  'Metricas de performance melhoraram',
  'Documentar alteracoes, Aplicar em outros ambientes',
  'tune-mysql.sh, analyze-queries.sql',
  '',
  'https://github.com/company/database',
  'Executar em janela de manutencao',
  'Metricas antes e depois, Configuracoes alteradas',
  'Arquivo my.cnf atualizado',
  '2 horas',
  'Degradacao de performance, Configuracao incorreta',
  'Testar em ambiente de desenvolvimento',
  'Reverter configuracao anterior'),

(UUID(), 'FIRE-00001', 'Configuracao Firewall Regras', 'Adicionar novas regras ao firewall', 'Procedimento de Rotina',
  'Acesso ao firewall, Permissoes administrativas',
  'Validar necessidade da regra, Documentar justificativa',
  'iptables/firewalld, nmap para testes',
  'Backup regras atuais\nAdicionar nova regra\nTestar conectividade\nValidar nao impactou trafego existente\nSalvar configuracao',
  'Regra incorreta pode bloquear trafego legitimo',
  'Testar conectividade, Validar servicos',
  'Regra adicionada e funcionando, Trafego normal',
  'Servicos ficaram inacessiveis, Regra bloqueando trafego',
  'Testar de multiplas origens, Validar logs do firewall',
  'Monitorar logs de conexoes bloqueadas',
  'Firewall permitindo trafego necessario',
  'Documentar regra adicionada, Atualizar diagrama',
  'add-firewall-rule.sh',
  '',
  'https://github.com/company/network',
  'Validar com equipe de seguranca',
  'Output do iptables -L',
  'Backup das regras, Nova configuracao',
  '20 minutos',
  'Bloqueio de trafego legitimo',
  'Sempre fazer backup antes, Testar em horario seguro',
  'Restaurar backup de regras'),

(UUID(), 'AUDT-00001', 'Auditoria Acessos Sistema', 'Revisar logs de acesso e identificar anomalias', 'Procedimento de Rotina',
  'Acesso aos logs de auditoria, Ferramentas de analise',
  'Definir periodo a ser auditado, Conhecer padroes normais',
  'Kibana, grep, awk, scripts de analise',
  'Exportar logs do periodo\nFiltrar logins fora do horario\nIdentificar multiplas falhas de login\nVerificar acessos de IPs desconhecidos\nGerar relatorio',
  'Analise pode revelar atividades suspeitas',
  'Validar cada anomalia encontrada',
  'Relatorio gerado, Anomalias documentadas',
  'Impossivel gerar relatorio, Logs corrompidos',
  'Investigar cada anomalia, Contatar usuarios se necessario',
  'Revisar eventos de seguranca',
  'Auditoria completa e documentada',
  'Enviar relatorio para seguranca, Criar tickets para investigacao',
  'audit-access-logs.sh, generate-report.py',
  'Cron weekly-audit',
  'https://github.com/company/security',
  'Executar semanalmente',
  'Relatorio de auditoria, Logs filtrados',
  'Relatorio PDF de auditoria',
  '1 hora',
  'Nao identificar atividade maliciosa',
  'Automatizar analise, Definir alertas',
  'Bloquear usuarios suspeitos, Resetar senhas'),

(UUID(), 'INTE-00001', 'Teste Integracao APIs', 'Executar testes de integracao entre APIs', 'Procedimento de Rotina',
  'Acesso aos ambientes, Colecao de testes Postman',
  'Validar ambiente esta estavel, Dados de teste prontos',
  'Postman, Newman, scripts de teste',
  'Importar colecao no Postman\nConfigurar variaveis de ambiente\nExecutar testes\nValidar respostas\nGerar relatorio',
  'Testes podem criar dados temporarios',
  'Verificar taxa de sucesso, Analisar falhas',
  'Todos testes passaram, APIs funcionando',
  'Testes falharam, APIs com erro',
  'Executar testes individualmente para debug',
  'Analisar logs das APIs',
  'Integracao validada e funcionando',
  'Documentar resultados, Reportar bugs encontrados',
  'run-integration-tests.sh',
  'Jenkins integration-tests',
  'https://github.com/company/tests',
  'Executar apos cada deploy',
  'Relatorio de testes do Newman',
  'Resultados dos testes em JSON',
  '30 minutos',
  'Testes falhando por problema de configuracao',
  'Manter dados de teste atualizados',
  'Corrigir configuracao, Re-executar'),

(UUID(), 'CACH-00001', 'Limpeza Cache Aplicacao', 'Limpar cache da aplicacao para liberar memoria', 'Procedimento de Rotina',
  'Acesso ao servidor de cache, Conhecimento da arquitetura',
  'Verificar uso de memoria, Identificar cache obsoleto',
  'Redis CLI, Memcached telnet',
  'Conectar ao Redis\nExecutar FLUSHDB para limpar database\nOu FLUSHALL para limpar tudo\nVerificar memoria liberada\nMonitorar aplicacao',
  'Limpeza pode causar pico temporario de latencia',
  'Monitorar uso de memoria, Validar aplicacao',
  'Memoria liberada, Cache reconstruindo',
  'Aplicacao com erros apos limpeza',
  'Testar funcionalidades criticas',
  'Monitorar logs da aplicacao',
  'Cache funcionando normalmente',
  'Documentar quantidade de memoria liberada',
  'flush-cache.sh',
  '',
  'https://github.com/company/cache',
  'Executar quando memoria > 80%',
  'Output do INFO memory',
  'Metricas antes e depois',
  '5 minutos',
  'Indisponibilidade da aplicacao',
  'Executar em horario de baixo uso',
  'Reiniciar servico de cache'),

(UUID(), 'REDE-00001', 'Configuracao VLAN Switch', 'Configurar nova VLAN no switch de rede', 'Procedimento de Rotina',
  'Acesso ao switch, Conhecimento de redes',
  'Planejar range de IPs, Documentar proposito da VLAN',
  'Terminal SSH, Cisco/HP switch CLI',
  'Conectar ao switch via SSH\nEntrar em modo config\nCriar VLAN\nAssociar portas\nConfigurar trunking\nSalvar configuracao\nTestar conectividade',
  'Configuracao incorreta pode afetar outras VLANs',
  'Testar ping entre dispositivos',
  'VLAN criada e funcional, Dispositivos comunicando',
  'Dispositivos nao se comunicam, VLAN incorreta',
  'Validar configuracao com diagrama de rede',
  'Verificar logs do switch',
  'VLAN operacional e documentada',
  'Atualizar diagrama de rede, Documentar VLAN',
  'configure-vlan.sh',
  '',
  'https://github.com/company/network',
  'Coordenar com equipe de rede',
  'Show vlan output, Show interfaces',
  'Configuracao do switch',
  '45 minutos',
  'Impacto em VLANs existentes',
  'Testar em switch de laboratorio primeiro',
  'Remover VLAN, Restaurar configuracao'),

(UUID(), 'SYNC-00001', 'Sincronizacao Repositorios Git', 'Sincronizar repositorio local com remoto', 'Procedimento de Rotina',
  'Acesso ao repositorio Git, Permissoes de push',
  'Verificar nao ha conflitos pendentes, Commit local feito',
  'Git CLI, editor de merge',
  'git fetch origin\ngit pull origin main\nResolver conflitos se houver\ngit push origin main\nValidar sincronizacao',
  'Pode haver conflitos que precisam resolucao manual',
  'Verificar status do repositorio',
  'Repositorio sincronizado sem conflitos',
  'Conflitos nao resolvidos, Erro no push',
  'Validar codigo apos merge',
  'Verificar logs do Git',
  'Codigo atualizado e sincronizado',
  'Notificar equipe sobre atualizacao',
  'sync-repo.sh',
  '',
  'https://github.com/company/development',
  'Executar antes de iniciar desenvolvimento',
  'Git log output',
  'Codigo sincronizado',
  '10 minutos',
  'Perder alteracoes locais, Conflitos complexos',
  'Sempre commitar antes de sincronizar',
  'Usar git reflog para recuperar alteracoes');
